import {
  Tag,
  Monitor,
  Car,
  Armchair,
  Building2,
  Radio,
  BookOpenCheck,
  Fingerprint,
  ShieldCheck,
  Shirt,
  Laptop,
  Server,
  Printer,
  Camera,
  Wrench,
  Briefcase,
  Package,
  Boxes,
  Truck,
  Plane,
  Ship,
  Hammer,
  HardHat,
  Cpu,
  HardDrive,
  Wifi,
  Phone,
  Smartphone,
  Tv,
  Lightbulb,
  Battery,
  Stethoscope,
  FlaskConical,
  Beaker,
  Microscope,
  GraduationCap,
  Library,
  Book,
  FileText,
  Folder,
  Key,
  Lock,
  Banknote,
  Landmark,
  Home,
  Factory,
  Warehouse,
  Tent,
  TreePine,
  Leaf,
  type LucideIcon,
} from "lucide-react";

export type IconOption = { name: string; label: string; icon: LucideIcon };

export const ICON_OPTIONS: IconOption[] = [
  { name: "tag", label: "Tag", icon: Tag },
  { name: "monitor", label: "Monitor", icon: Monitor },
  { name: "laptop", label: "Laptop", icon: Laptop },
  { name: "server", label: "Server", icon: Server },
  { name: "cpu", label: "CPU", icon: Cpu },
  { name: "hard-drive", label: "Hard drive", icon: HardDrive },
  { name: "printer", label: "Printer", icon: Printer },
  { name: "tv", label: "TV", icon: Tv },
  { name: "phone", label: "Phone", icon: Phone },
  { name: "smartphone", label: "Smartphone", icon: Smartphone },
  { name: "wifi", label: "Wi-Fi", icon: Wifi },
  { name: "radio", label: "Radio", icon: Radio },
  { name: "camera", label: "Camera", icon: Camera },
  { name: "fingerprint", label: "Fingerprint", icon: Fingerprint },
  { name: "shield-check", label: "Shield", icon: ShieldCheck },
  { name: "key", label: "Key", icon: Key },
  { name: "lock", label: "Lock", icon: Lock },
  { name: "book-open-check", label: "Document", icon: BookOpenCheck },
  { name: "book", label: "Book", icon: Book },
  { name: "library", label: "Library", icon: Library },
  { name: "graduation-cap", label: "Education", icon: GraduationCap },
  { name: "file-text", label: "File", icon: FileText },
  { name: "folder", label: "Folder", icon: Folder },
  { name: "briefcase", label: "Briefcase", icon: Briefcase },
  { name: "armchair", label: "Furniture", icon: Armchair },
  { name: "shirt", label: "Uniform", icon: Shirt },
  { name: "hammer", label: "Hammer", icon: Hammer },
  { name: "wrench", label: "Wrench", icon: Wrench },
  { name: "hard-hat", label: "Hard hat", icon: HardHat },
  { name: "package", label: "Package", icon: Package },
  { name: "boxes", label: "Boxes", icon: Boxes },
  { name: "warehouse", label: "Warehouse", icon: Warehouse },
  { name: "factory", label: "Factory", icon: Factory },
  { name: "building-2", label: "Building", icon: Building2 },
  { name: "home", label: "Home", icon: Home },
  { name: "landmark", label: "Landmark", icon: Landmark },
  { name: "tent", label: "Tent", icon: Tent },
  { name: "car", label: "Car", icon: Car },
  { name: "truck", label: "Truck", icon: Truck },
  { name: "plane", label: "Plane", icon: Plane },
  { name: "ship", label: "Ship", icon: Ship },
  { name: "battery", label: "Battery", icon: Battery },
  { name: "lightbulb", label: "Lightbulb", icon: Lightbulb },
  { name: "stethoscope", label: "Medical", icon: Stethoscope },
  { name: "flask-conical", label: "Lab flask", icon: FlaskConical },
  { name: "beaker", label: "Beaker", icon: Beaker },
  { name: "microscope", label: "Microscope", icon: Microscope },
  { name: "banknote", label: "Banknote", icon: Banknote },
  { name: "leaf", label: "Leaf", icon: Leaf },
  { name: "tree-pine", label: "Tree", icon: TreePine },
];

const ICON_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.icon]),
);

export function getIconByName(name?: string | null): LucideIcon | null {
  if (!name) return null;
  return ICON_BY_NAME[name] ?? null;
}

export type ColorOption = { value: string; label: string };

// Curated palette (hex). Tailwind-ish swatches at ~500 weight.
export const COLOR_OPTIONS: ColorOption[] = [
  { value: "#ef4444", label: "Red" },
  { value: "#f97316", label: "Orange" },
  { value: "#f59e0b", label: "Amber" },
  { value: "#eab308", label: "Yellow" },
  { value: "#84cc16", label: "Lime" },
  { value: "#22c55e", label: "Green" },
  { value: "#10b981", label: "Emerald" },
  { value: "#14b8a6", label: "Teal" },
  { value: "#06b6d4", label: "Cyan" },
  { value: "#0ea5e9", label: "Sky" },
  { value: "#3b82f6", label: "Blue" },
  { value: "#6366f1", label: "Indigo" },
  { value: "#8b5cf6", label: "Violet" },
  { value: "#a855f7", label: "Purple" },
  { value: "#d946ef", label: "Fuchsia" },
  { value: "#ec4899", label: "Pink" },
  { value: "#f43f5e", label: "Rose" },
  { value: "#64748b", label: "Slate" },
];
